name: Android APK Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Kodu Cek
      uses: actions/checkout@v4

    - name: Sistem Bagimliliklarini Kur
      run: |
        sudo apt-get update
        sudo apt-get install -y libunwind-dev
        sudo apt-get install -y \
          build-essential \
          git \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly \
          gstreamer1.0-libav \
          libsqlite3-dev \
          sqlite3 \
          libgirepository1.0-dev \
          libcairo2-dev \
          pkg-config \
          python3-dev \
          python3-pip \
          zip \
          unzip \
          openjdk-17-jdk

    - name: Python ve Buildozer Kur
      run: |
        pip3 install --user --upgrade pip
        pip3 install --user --upgrade buildozer cython virtualenv

    # HATA VEREN LİSANS SORUNUNU BURADA ÇÖZÜYORUZ:
    - name: APK Derle (Buildozer)
      run: |
        export PATH=$PATH:~/.local/bin
        # Buildozer'ın Android SDK lisanslarını otomatik olarak onaylamasını sağlıyoruz
        yes | buildozer -v android debug
        
    - name: APK Dosyasini Yayinla
      uses: actions/upload-artifact@v4
      with:
        name: SpaceWarx-Android-APK
        path: bin/*.apk
